In [1]:
class Point2D:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __add__(self, pt):
        new_x = self.x + pt.x
        new_y = self.y + pt.y
        return Point2D(new_x, new_y)
    def __str__(self):
        return '({}, {})'.format(self.x, self.y)    

In [2]:
p1 = Point2D(3, 5)
p2 = Point2D(-1, 1)

In [3]:
p3 = p1 + p2

In [4]:
print(p1, p2, p3)

(3, 5) (-1, 1) (2, 6)


## Numpy

In [5]:
import numpy as np

In [8]:
arr1 = np.array([1, 2, 3])
print(arr1, arr1.shape, type(arr1))

[1 2 3] (3,) <class 'numpy.ndarray'>


In [10]:
arr2 = np.array([arr1, arr1, arr1, arr1])
print(arr2, arr2.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]] (4, 3)


In [11]:
arr3 = np.array([arr2, arr2])
print(arr3, arr3.shape)

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]] (2, 4, 3)


In [13]:
arr4 = np.array([arr3, arr3, arr3])
print(arr4, arr4.shape)

[[[[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]
   [1 2 3]]]] (3, 2, 4, 3)


In [14]:
arr = np.array([[1], [1], [1]]) # int arr[3][1]
print(arr, arr.shape)

[[1]
 [1]
 [1]] (3, 1)


In [15]:
arr = np.array([[[1]]])  # int arr[1][1][1]
print(arr, arr.shape)

[[[1]]] (1, 1, 1)


In [16]:
zeros = np.zeros([3, 4])
print(zeros, zeros.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)


In [17]:
len(zeros)

3

In [18]:
ones = np.ones([3, 4])
print(ones, ones.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)


array([0, 1, 2, 3, 4])

In [25]:
arr = np.arange(12)
arr = arr.reshape(3,4) # arr = np.arange(12).reshape(3,4)
print(arr, arr.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [23]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
data = np.random.randn(3,4)
print(data, data.shape)

[[ 0.09632889  1.13427907 -0.00527823 -0.22596676]
 [-0.41137219 -0.9267819  -2.46921105 -0.37371528]
 [ 0.41747399  0.68105558 -0.754559   -0.62945583]] (3, 4)


In [34]:
bin = data <= 1

In [35]:
print(bin)

[[ True False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [36]:
data[data <= 1] = 100

In [37]:
print(data)

[[100.           1.13427907 100.         100.        ]
 [100.         100.         100.         100.        ]
 [100.         100.         100.         100.        ]]


In [38]:
data + np.array([1,2,3,4])

array([[101.        ,   3.13427907, 103.        , 104.        ],
       [101.        , 102.        , 103.        , 104.        ],
       [101.        , 102.        , 103.        , 104.        ]])

In [39]:
arr = np.random.randint(2, size=12).reshape(3,4)
print(arr, arr.shape)

[[1 0 1 0]
 [0 0 1 1]
 [0 1 0 0]] (3, 4)


In [43]:
np.sum(arr, axis = 0), np.sum(arr, axis=1), np.sum(arr)

(array([1, 1, 2, 1]), array([2, 2, 1]), np.int64(5))

In [46]:
arr = np.random.randint(3, size=12).reshape(3,4)
print(arr)
np.max(arr, axis = 0), np.max(arr, axis=1), np.max(arr)

[[2 1 1 1]
 [0 1 0 2]
 [1 1 1 0]]


(array([2, 1, 1, 2], dtype=int32), array([2, 2, 1], dtype=int32), np.int32(2))

In [47]:
arr = np.random.randint(3, size=12).reshape(3,4)
print(arr)
np.min(arr, axis = 0), np.min(arr, axis=1), np.min(arr)

[[2 2 0 2]
 [2 2 2 1]
 [2 1 0 2]]


(array([2, 1, 0, 1], dtype=int32), array([0, 1, 0], dtype=int32), np.int32(0))

In [48]:
arr = np.random.randint(3, size=12).reshape(3,4)
print(arr)
np.mean(arr, axis = 0), np.mean(arr, axis=1), np.mean(arr)

[[2 1 1 0]
 [0 0 0 0]
 [0 1 2 1]]


(array([0.66666667, 0.66666667, 1.        , 0.33333333]),
 array([1., 0., 1.]),
 np.float64(0.6666666666666666))

In [53]:
arr = np.random.randint(10, size=12).reshape(3,4)
print(arr)
np.argmax(arr, axis = 0), np.argmax(arr, axis=1), np.argmax(arr)

[[5 4 2 2]
 [2 2 6 9]
 [7 2 9 1]]


(array([2, 0, 2, 1]), array([0, 3, 2]), np.int64(7))

In [55]:
arr = np.random.randint(10, size=12).reshape(3,4)
print(arr)
np.argmin(arr, axis = 0), np.argmin(arr, axis=1), np.argmin(arr)

[[7 4 4 2]
 [0 0 0 9]
 [7 8 9 8]]


(array([1, 1, 1, 0]), array([3, 0, 0]), np.int64(4))

In [58]:
arr = np.random.randint(10, size = 20)
print(arr, arr.shape)

[8 7 2 7 8 4 4 2 4 3 4 0 6 7 7 9 5 8 4 2] (20,)


In [59]:
np.unique(arr)

array([0, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)