In [1]:
import numpy as np

In [2]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
z = np.array([[0], [1], [1], [1]])
print(X, X.shape)
print(z, z.shape)

[[0 0]
 [0 1]
 [1 0]
 [1 1]] (4, 2)
[[0]
 [1]
 [1]
 [1]] (4, 1)


In [3]:
def sigmoid(y):
    return 1/(1+np.exp(-y))

In [8]:
sigmoid(np.array([0, 1, 2]))

array([0.5       , 0.73105858, 0.88079708])

In [4]:
def sigmoid_derivative(z_hat):
    return z_hat * (1-z_hat)

In [5]:
np.random.seed(1000)
w = np.random.randn(2, 1)
b = np.zeros((1, 1))

print(w, w.shape)
print(b, b.shape)

[[-0.8044583 ]
 [ 0.32093155]] (2, 1)
[[0.]] (1, 1)


In [6]:
layer0 = X
y = np.dot(X, w) + b
layer1 = sigmoid(y)
print(y, y.shape)
print(np.dot(X, w))
print(layer1)

[[ 0.        ]
 [ 0.32093155]
 [-0.8044583 ]
 [-0.48352676]] (4, 1)
[[ 0.        ]
 [ 0.32093155]
 [-0.8044583 ]
 [-0.48352676]]
[[0.5       ]
 [0.57955126]
 [0.30907265]
 [0.38141968]]


In [9]:
def forward_compute(X, w, b):
    layer0 = X
    y = np.dot(X, w) + b
    layer1 = sigmoid(y)
    return layer0, layer1

In [10]:
np.dot(X, w), X.shape, w.shape

(array([[ 0.        ],
        [ 0.32093155],
        [-0.8044583 ],
        [-0.48352676]]),
 (4, 2),
 (2, 1))

In [15]:
learning_rate = 0.1
layer0, layer1 = forward_compute(X, w, b)

decision = (layer1 >= 0.5)
error = np.sum(np.abs(decision-z))
loss = np.sum(np.abs(layer1 - z))
print(error, loss, layer1.T)
#if error == 0: break

layer1_error = layer1 - z
layer1_delta = layer1_error * sigmoid_derivative(layer1)

print(layer1_error)
print(layer1_delta)

3 2.2299564067322133 [[0.5        0.57955126 0.30907265 0.38141968]]
[[ 0.5       ]
 [-0.42044874]
 [-0.69092735]
 [-0.61858032]]
[[ 0.125     ]
 [-0.10245142]
 [-0.14754529]
 [-0.14594704]]


In [20]:
print(X.T)
print(X.T.shape, layer1_delta.shape)
print(len(X))

[[0 0 1 1]
 [0 1 0 1]]
(2, 4) (4, 1)
4


In [ ]:
dw = np.dot(X.T, layer1_delta) / len(X)
db = np.sum(layer1_delta) / len(X)

w -= learning_rate * dw
b -= learning_rate * db

In [ ]:
learning_rate = 0.1
for epoch in range(1000):
    layer0, layer1 = forward_compute(X, w, b)

    decision = (layer1 >= 0.5)
    error = np.sum(np.abs(decision-z))
    loss = np.sum(np.abs(layer1 - z))
    print(epoch, error, loss, layer1.T)
    if error == 0: break

    layer1_error = layer1 - z
    layer1_delta = layer1_error * sigmoid_derivative(layer1)

    dw = np.dot(X.T, layer1_delta) / len(X)
    db = np.sum(layer1_delta) / len(X)

    w -= learning_rate * dw
    b -= learning_rate * db

In [ ]:
w, b