In [2]:
import numpy as np

In [3]:
X = np.array([[-1, -1], [-1, 1], [1, -1], [1, 1]])
z = np.array([[-1], [1], [1], [1]])
print(X, X.shape)
print(z, z.shape)

[[-1 -1]
 [-1  1]
 [ 1 -1]
 [ 1  1]] (4, 2)
[[-1]
 [ 1]
 [ 1]
 [ 1]] (4, 1)


In [4]:
def sigmoid(y):
    return 2.0/(1+np.exp(-y)) - 1.0

In [5]:
sigmoid(np.array([0, 1, 2]))

array([0.        , 0.46211716, 0.76159416])

In [6]:
def sigmoid_derivative(y):
    z = sigmoid(y)
    return 0.5 * (1-z) * (1+z)

In [16]:
np.random.seed(1000)
w = np.random.randn(2, 1)
b = np.zeros((1, 1))

print(w, w.shape)
print(b, b.shape)

[[-0.8044583 ]
 [ 0.32093155]] (2, 1)
[[0.]] (1, 1)


In [17]:
layer0 = X
y = np.dot(X, w) + b
layer1 = sigmoid(y)
print(y, y.shape)
print(np.dot(X, w))
print(layer1)

[[ 0.48352676]
 [ 1.12538985]
 [-1.12538985]
 [-0.48352676]] (4, 1)
[[ 0.48352676]
 [ 1.12538985]
 [-1.12538985]
 [-0.48352676]]
[[ 0.23716064]
 [ 0.50997422]
 [-0.50997422]
 [-0.23716064]]


In [9]:
def forward_compute(X, w, b):
    layer0 = X
    y = np.dot(X, w) + b
    layer1 = sigmoid(y)
    return layer0, layer1

In [10]:
np.dot(X, w), X.shape, w.shape

(array([[ 0.        ],
        [ 0.32093155],
        [-0.8044583 ],
        [-0.48352676]]),
 (4, 2),
 (2, 1))

In [11]:
learning_rate = 0.1
layer0, layer1 = forward_compute(X, w, b)

decision = layer1.copy()
decision[decision>=0] = 1
decision[decision<0] = -1
error = np.sum(np.abs(decision-z))
loss = np.sum(np.abs(layer1 - z))
print(error, loss, layer1.T)
#if error == 0: break

layer1_error = layer1 - z
layer1_delta = layer1_error * sigmoid_derivative(layer1)

print(layer1_error)
print(layer1_delta)

6.0 4.47432128157507 [[ 0.23716064  0.50997422 -0.50997422 -0.23716064]]
[[ 1.23716064]
 [-0.49002578]
 [-1.50997422]
 [-1.23716064]]
[[ 0.60996317]
 [-0.22974844]
 [-0.70795097]
 [-0.60996317]]


In [20]:
print(X.T)
print(X.T.shape, layer1_delta.shape)
print(len(X))

[[0 0 1 1]
 [0 1 0 1]]
(2, 4) (4, 1)
4


In [ ]:
dw = np.dot(X.T, layer1_delta) / len(X)
db = np.sum(layer1_delta) / len(X)

w -= learning_rate * dw
b -= learning_rate * db

In [18]:
learning_rate = 0.1
for epoch in range(1000):
    layer0, layer1 = forward_compute(X, w, b)

    decision = layer1.copy()
    decision[decision>=0] = 1
    decision[decision<0] = -1
    error = np.sum(np.abs(decision-z))
    loss = np.sum(np.abs(layer1 - z))
    print(epoch, int(error), loss, layer1.T)
    #if error == 0: break

    layer1_error = layer1 - z
    layer1_delta = layer1_error
    #layer1_delta = layer1_error * sigmoid_derivative(layer1)

    dw = np.dot(X.T, layer1_delta) / len(X)
    db = np.sum(layer1_delta) / len(X)

    w -= learning_rate * dw
    b -= learning_rate * db

0 6 4.47432128157507 [[ 0.23716064  0.50997422 -0.50997422 -0.23716064]]
1 6 4.317812576723898 [[ 0.20208497  0.50960512 -0.47165462 -0.15367811]]
2 6 4.1642591180190625 [[ 0.16831478  0.50915268 -0.43313091 -0.07196611]]
3 4 4.015225469448314 [[ 0.13592367  0.50862527 -0.39468862  0.00676155]]
4 4 3.8718893323024552 [[ 0.10494548  0.50803895 -0.35658389  0.08160109]]
5 4 3.735049235287776 [[ 0.07538142  0.50741505 -0.31903834  0.15195547]]
6 4 3.6051665199678364 [[ 0.04720751  0.50677786 -0.28223715  0.21750027]]
7 4 3.482425013114562 [[ 0.02038151  0.5061526  -0.2463295   0.2781334 ]]
8 2 3.3667949663063377 [[-0.00515105  0.50556381 -0.21143077  0.33392095]]
9 2 3.2580924939463323 [[-0.02945206  0.50503423 -0.17762575  0.38504697]]
10 2 3.1560300213447188 [[-0.05258709  0.50458412 -0.14497243  0.4317712 ]]
11 2 3.060256368406545 [[-0.07462266  0.50423082 -0.11350584  0.47439599]]
12 2 2.9703869704166586 [[-0.09562432  0.50398868 -0.08324184  0.51324186]]
13 2 2.88602564251251 [[-0.11

In [19]:
w, b

(array([[3.87922396],
        [3.87923136]]),
 array([[3.87922965]]))