In [2]:
import numpy as np

In [3]:
X = np.array([[-1, -1], [-1, 1], [1, -1], [1, 1]])
z = np.array([[-1], [1], [1], [1]])

In [12]:
def sigmoid(y):
    return 2.0/(1+np.exp(-y)) - 1.0

In [13]:
def sigmoid_derivative(y):
    z = sigmoid(y)
    return 0.5 * (1-z) * (1+z)

In [14]:
np.random.seed(1000)
w = np.random.randn(2, 1)
b = np.zeros((1, 1))

In [15]:
def forward_compute(X, w, b):
    layer0 = X
    y = np.dot(X, w) + b
    layer1 = sigmoid(y)
    return layer0, layer1

In [20]:
np.dot(X, w), X.shape, w.shape

(array([[ 0.        ],
        [ 0.32093155],
        [-0.8044583 ],
        [-0.48352676]]),
 (4, 2),
 (2, 1))

In [19]:
learning_rate = 0.1
for epoch in range(1000):
    layer0, layer1 = forward_compute(X, w, b)

    decision = layer1.copy()
    decision[decision>=0] = 1
    decision[decision<0] = -1
    error = np.sum(np.abs(decision-z))
    loss = np.sum(np.abs(layer1 - z))
    print(epoch, int(error), loss, layer1.T)
    #if error == 0: break

    layer1_error = layer1 - z
    layer1_delta = layer1_error * sigmoid_derivative(layer1)

    dw = np.dot(X.T, layer1_delta) / len(X)
    db = np.sum(layer1_delta) / len(X)

    w -= learning_rate * dw
    b -= learning_rate * db

0 0 0.2699151781528377 [[-0.91009529  0.9101065   0.91009155  0.99979149]]
1 0 0.2696772488890232 [[-0.91017442  0.91018557  0.91017069  0.99979206]]
2 0 0.2694397383850057 [[-0.91025341  0.91026451  0.9102497   0.99979264]]
3 0 0.2692026455363321 [[-0.91033226  0.91034332  0.91032857  0.99979321]]
4 0 0.2689659692424272 [[-0.91041098  0.91042198  0.9104073   0.99979378]]
5 0 0.26872970840658394 [[-0.91048955  0.91050051  0.91048589  0.99979435]]
6 0 0.26849386193594216 [[-0.91056799  0.9105789   0.91056434  0.99979491]]
7 0 0.2682584287414732 [[-0.91064629  0.91065715  0.91064266  0.99979548]]
8 0 0.26802340773796274 [[-0.91072445  0.91073526  0.91072084  0.99979604]]
9 0 0.26778879784399245 [[-0.91080248  0.91081324  0.91079888  0.9997966 ]]
10 0 0.2675545979819267 [[-0.91088037  0.91089109  0.91087679  0.99979715]]
11 0 0.2673208070778935 [[-0.91095813  0.91096879  0.91095456  0.99979771]]
12 0 0.2670874240617701 [[-0.91103575  0.91104637  0.9110322   0.99979826]]
13 0 0.26685444786

In [20]:
w, b

(array([[3.71017673],
        [3.71018318]]),
 array([[3.71018156]]))