In [1]:
import numpy as np

In [2]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
z = np.array([[0], [1], [1], [1]])

In [12]:
def sigmoid(y):
    return 1/(1+np.exp(-y))

In [4]:
def sigmoid_derivative(z_hat):
    return z_hat * (1-z_hat)

In [18]:
np.random.seed(1000)
w = np.random.randn(2, 1)
b = np.zeros((1, 1))

In [19]:
def forward_compute(X, w, b):
    layer0 = X
    y = np.dot(X, w) + b
    layer1 = sigmoid(y)
    return layer0, layer1

In [20]:
np.dot(X, w), X.shape, w.shape

(array([[ 0.        ],
        [ 0.32093155],
        [-0.8044583 ],
        [-0.48352676]]),
 (4, 2),
 (2, 1))

In [21]:
learning_rate = 0.1
for epoch in range(1000):
    layer0, layer1 = forward_compute(X, w, b)

    decision = (layer1 >= 0.5)
    error = np.sum(np.abs(decision-z))
    loss = np.sum(np.abs(layer1 - z))
    print(epoch, error, loss, layer1.T)
    if error == 0: break

    layer1_error = layer1 - z
    layer1_delta = layer1_error * sigmoid_derivative(layer1)

    dw = np.dot(X.T, layer1_delta) / len(X)
    db = np.sum(layer1_delta) / len(X)

    w -= learning_rate * dw
    b -= learning_rate * db

0 3 2.2299564067322133 [[0.5        0.57955126 0.30907265 0.38141968]]
1 3 2.2206620630626364 [[0.50169339 0.58271168 0.31209408 0.38622557]]
2 3 2.2113759357218923 [[0.50337604 0.58584623 0.31512068 0.39103319]]
3 3 2.202101215302337 [[0.50504761 0.5889543  0.31815152 0.39584057]]
4 3 2.1928410560858898 [[0.50670775 0.59203528 0.32118568 0.40064573]]
5 3 2.183598569929218 [[0.50835614 0.5950886  0.32422222 0.40544674]]
6 3 2.174376820378414 [[0.50999246 0.59811373 0.32726022 0.41024169]]
7 3 2.1651788170396205 [[0.51161642 0.60111016 0.33029876 0.41502868]]
8 3 2.15600751022963 [[0.51322772 0.60407743 0.33333694 0.41980584]]
9 3 2.1468657859279094 [[0.51482609 0.60701509 0.33637384 0.42457137]]
10 3 2.1377564610487627 [[0.51641125 0.60992276 0.33940858 0.42932346]]
11 3 2.1286822790495363 [[0.51798297 0.61280005 0.34244027 0.43406037]]
12 3 2.1196459058878996 [[0.51954099 0.61564663 0.34546805 0.4387804 ]]
13 3 2.1106499263383443 [[0.52108509 0.6184622  0.34849107 0.44348189]]
14 3 2.

In [15]:
w, b

(array([[2.86930961],
        [2.30955982]]),
 array([[-0.00197024]]))